version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: parser-db
    environment:
      POSTGRES_DB: parser-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - parser-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d parser-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parser-app
    environment:
      DB_URL: jdbc:postgresql://parser-db:5432/parser-db
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parser-network

    stdin_open: true
    tty: true

networks:
  parser-network:
    driver: bridge