xml:
  url: https://expro.ru/bitrix/catalog_export/export_Sai.xml
  connection:
    request-method: GET
    connect-timeout: 3000
    read-timeout: 3000
    user-agent: "Mozilla/5.0"

spring:
  application:
    name: xml-processor

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/parser-db}
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.task: INFO
    org.springframework.boot: INFO
    org.springframework.jdbc: OFF
